#!/bin/bash

DIR="/home/jeeto/Desktop"
DIR_PFA="$DIR/python-for-android"
DIR_JPFA="$DIR/jap-python-for-android"
VERSION="1.0.0-SNAPSHOT"

export ANDROIDSDK="$DIR/adt-bundle-linux-x86/sdk"
export ANDROIDNDK="$DIR/android-ndk-r7c"
export ANDROIDNDKVER=r7c
export ANDROIDAPI=14

bash "$DIR_PFA/distribute.sh" -m "openssl pyopenssl zope twisted" -d "P4A-$VERSION"

rm -rf "$DIR_JPFA/dist"
mkdir -p "$DIR_JPFA/dist"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python/bin"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/bin/python" "$DIR_JPFA/dist/P4A-$VERSION/files/python/bin/python"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python/include"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/include/"* "$DIR_JPFA/dist/P4A-$VERSION/files/python/include"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/lib/libpython2.7.so" "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/libpython2.7.so"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/python2.7"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/python2.7/config"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/lib/python2.7/config/"* "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/python2.7/config"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/python2.7/lib-dynload"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/lib/python2.7/lib-dynload/"* "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/python2.7/lib-dynload"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/python2.7/OpenSSL"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/lib/python2.7/site-packages/OpenSSL/"* "$DIR_JPFA/dist/P4A-$VERSION/files/python/lib/python2.7/OpenSSL"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/extras"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/extras/python"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/lib/python2.7/"* "$DIR_JPFA/dist/P4A-$VERSION/extras/python"
rm -r "$DIR_JPFA/dist/P4A-$VERSION/extras/python/config"
rm -r "$DIR_JPFA/dist/P4A-$VERSION/extras/python/lib-dynload"
rm -r "$DIR_JPFA/dist/P4A-$VERSION/extras/python/site-packages"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/extras/python/twisted"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/lib/python2.7/site-packages/twisted/"* "$DIR_JPFA/dist/P4A-$VERSION/extras/python/twisted"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/extras/python/zope"
cp -r "$DIR_PFA/dist/P4A-$VERSION/python-install/lib/python2.7/site-packages/zope/"* "$DIR_JPFA/dist/P4A-$VERSION/extras/python/zope"
mkdir -p "$DIR_JPFA/dist/P4A-$VERSION/extras/python/autobahn"
cp -r "$DIR_JPFA/src/extras/python/autobahn/"* "$DIR_JPFA/dist/P4A-$VERSION/extras/python/autobahn"
cp -r "$DIR_JPFA/src/python.sh" "$DIR_JPFA/dist/P4A-$VERSION/python.sh"
cp -r "$DIR_JPFA/src/python_install.sh" "$DIR_JPFA/dist/P4A-$VERSION/python_install.sh"
cp -r "$DIR_JPFA/src/python_uninstall.sh" "$DIR_JPFA/dist/P4A-$VERSION/python_uninstall.sh"
cp -r "$DIR_JPFA/src/README.txt" "$DIR_JPFA/dist/P4A-$VERSION/README.txt"
cd "$DIR_JPFA/dist"
zip -r "P4A-$VERSION.zip" "P4A-$VERSION"
cd "$DIR_JPFA"

